In [1]:
"""
Getting realtime data feed from the MTA and separating based on N/S Bound trains
"""
from nyct_gtfs import NYCTFeed

feed = NYCTFeed("N")
trains = feed.filter_trips(line_id=['N'], underway=True)

# filtering based on n/s bound trains
northbound_trains = [train for train in trains if train.direction == 'N']
southbound_trains = [train for train in trains if train.direction == 'S']

# gathering all the individual trips
n_bound_trip_ids = [trip.trip_id for trip in northbound_trains]
s_bound_trip_ids = [trip.trip_id for trip in southbound_trains]

n_bound_trip_ids + s_bound_trip_ids

['099300_N..N33R',
 '100200_N..N16R',
 '101200_N..N33R',
 '101900_N..N33R',
 '102700_N..N33R',
 '103300_N..N33R',
 '104400_N..N33R',
 '105500_N..N33R',
 '106650_N..N33R',
 '099650_N..S34R',
 '101100_N..S34R',
 '101400_N..S16R',
 '101600_N..S34R',
 '102200_N..S34R',
 '102900_N..S34R',
 '103750_N..S34R',
 '104550_N..S34R',
 '105400_N..S34R',
 '106450_N..S34R']

In [2]:
"""
Creating data frame to hold scheduled times for each trip
Downloads GTFS data from https://rrgtfsfeeds.s3.amazonaws.com/gtfs_supplemented.zip
"""
import pandas as pd
import re
import requests
import zipfile
import io

# Download and extract the GTFS data
print("Downloading GTFS data...")
url = "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_supplemented.zip"
response = requests.get(url)
response.raise_for_status()  # Raise an exception for bad status codes

# Extract stop_times.txt from the zip file
print("Extracting stop_times.txt...")
with zipfile.ZipFile(io.BytesIO(response.content)) as zip_file:
    # Find the stop_times.txt file (it might be in a different path)
    stop_times_file_path = None
    for file_path in zip_file.namelist():
        if file_path.endswith('stop_times.txt'):
            stop_times_file_path = file_path
            break

    if stop_times_file_path is None:
        raise FileNotFoundError("stop_times.txt not found in the archive")

    with zip_file.open(stop_times_file_path) as stop_times_file:
        # Read the content and create a DataFrame
        stop_times = pd.read_csv(stop_times_file)

print(f"Successfully loaded stop_times data with {len(stop_times):,} rows")

# Process trip data if trip IDs are defined
trip_dfs = {}
if 'n_bound_trip_ids' in globals() and 's_bound_trip_ids' in globals():
    all_trip_ids = n_bound_trip_ids + s_bound_trip_ids

    for trip in all_trip_ids:
        escaped_trip = re.escape(trip)
        filtered = stop_times[stop_times['trip_id'].str.contains(escaped_trip, na=False)]
        trip_dfs[trip] = filtered

    print(f"Processed {len(trip_dfs)} trip DataFrames")
else:
    print("Trip IDs not defined - skipping trip processing. Define n_bound_trip_ids and s_bound_trip_ids variables.")

trip_dfs

Downloading GTFS data...
Extracting stop_times.txt...
Successfully loaded stop_times data with 2,266,327 rows
Processed 19 trip DataFrames

{'099300_N..N33R':                                          trip_id stop_id arrival_time  \
 496736   BSP25GEN-N100-Weekday-00_099300_N..N33R    D43N     16:33:00
 496737   BSP25GEN-N100-Weekday-00_099300_N..N33R    N10N     16:37:00
 496738   BSP25GEN-N100-Weekday-00_099300_N..N33R    N09N     16:38:00
 496739   BSP25GEN-N100-Weekday-00_099300_N..N33R    N08N     16:40:00
 496740   BSP25GEN-N100-Weekday-00_099300_N..N33R    N07N     16:42:00
 ...                                          ...     ...          ...
 2091880           L0S9-N-1100-S01_099300_N..N33R    R06N     17:45:30
 2091881           L0S9-N-1100-S01_099300_N..N33R    R05N     17:47:30
 2091882           L0S9-N-1100-S01_099300_N..N33R    R04N     17:49:00
 2091883           L0S9-N-1100-S01_099300_N..N33R    R03N     17:50:30
 2091884           L0S9-N-1100-S01_099300_N..N33R    R01N     17:52:30

         departure_time  stop_sequence
 496736        16:33:00              1
 496737        16:37:00              2
 496738        16:38:00              3
 496739        16:40:00              4
 496740        16:42:00              5
 ...                ...            ...
 2091880       17:45:30             24
 2091881       17:47:30             25
 2091882       17:49:00             26
 2091883       17:50:30             27
 2091884       17:52:30             28

 [196 rows x 5 columns],
 '100200_N..N16R':                                          trip_id stop_id arrival_time  \
 496860   BSP25GEN-N100-Weekday-00_100200_N..N16R    D43N     16:42:00
 496861   BSP25GEN-N100-Weekday-00_100200_N..N16R    N10N     16:46:00
 496862   BSP25GEN-N100-Weekday-00_100200_N..N16R    N09N     16:47:00
 496863   BSP25GEN-N100-Weekday-00_100200_N..N16R    N08N     16:49:00
 496864   BSP25GEN-N100-Weekday-00_100200_N..N16R    N07N     16:51:00
 ...                                          ...     ...          ...
 2091998           L0S9-N-1100-S01_100200_N..N16R    R14N     17:37:30
 2091999           L0S9-N-1100-S01_100200_N..N16R    B08N     17:41:00
 2092000           L0S9-N-1100-S01_100200_N..N16R    Q03N     17:43:00
 2092001           L0S9-N-1100-S01_100200_N..N16R    Q04N     17:45:00
 2092002           L0S9-N-1100-S01_100200_N..N16R    Q05N     17:46:30

         departure_time  stop_sequence
 496860        16:42:00              1
 496861        16:46:00              2
 496862        16:47:00              3
 496863        16:49:00              4
 496864        16:51:00              5
 ...                ...            ...
 2091998       17:38:00             18
 2091999       17:41:00             19
 2092000       17:43:00             20
 2092001       17:45:00             21
 2092002       17:46:30             22

 [154 rows x 5 columns],
 '101200_N..N33R':                                          trip_id stop_id arrival_time  \
 496956   BSP25GEN-N100-Weekday-00_101200_N..N33R    D43N     16:52:00
 496957   BSP25GEN-N100-Weekday-00_101200_N..N33R    N10N     16:56:00
 496958   BSP25GEN-N100-Weekday-00_101200_N..N33R    N09N     16:57:00
 496959   BSP25GEN-N100-Weekday-00_101200_N..N33R    N08N     16:59:00
 496960   BSP25GEN-N100-Weekday-00_101200_N..N33R    N07N     17:01:00
 ...                                          ...     ...          ...
 2092100           L0S9-N-1100-S01_101200_N..N33R    R06N     18:03:00
 2092101           L0S9-N-1100-S01_101200_N..N33R    R05N     18:05:00
 2092102           L0S9-N-1100-S01_101200_N..N33R    R04N     18:06:30
 2092103           L0S9-N-1100-S01_101200_N..N33R    R03N     18:08:00
 2092104           L0S9-N-1100-S01_101200_N..N33R    R01N     18:10:00

         departure_time  stop_sequence
 496956        16:52:00              1
 496957        16:56:00              2
 496958        16:57:00              3
 496959        16:59:00              4
 496960        17:01:00              5
 ...                ...            ...
 2092100       18:03:00             24
 2092101       18:05:00             25
 2092102       18:06:30             26
 2092103       18:08:00             27
 2092104       18:10:00             28

 [196 rows x 5 columns],
 '101900_N..N33R':                                          trip_id stop_id arrival_time  \
 497034   BSP25GEN-N100-Weekday-00_101900_N..N33R    D43N     16:59:00
 497035   BSP25GEN-N100-Weekday-00_101900_N..N33R    N10N     17:03:00
 497036   BSP25GEN-N100-Weekday-00_101900_N..N33R    N09N     17:04:00
 497037   BSP25GEN-N100-Weekday-00_101900_N..N33R    N08N     17:06:00
 497038   BSP25GEN-N100-Weekday-00_101900_N..N33R    N07N     17:08:00
 ...                                          ...     ...          ...
 2092178           L0S9-N-1100-S01_101900_N..N33R    R06N     18:10:00
 2092179           L0S9-N-1100-S01_101900_N..N33R    R05N     18:12:00
 2092180           L0S9-N-1100-S01_101900_N..N33R    R04N     18:13:30
 2092181           L0S9-N-1100-S01_101900_N..N33R    R03N     18:15:00
 2092182           L0S9-N-1100-S01_101900_N..N33R    R01N     18:17:00

         departure_time  stop_sequence
 497034        16:59:00              1
 497035        17:03:00              2
 497036        17:04:00              3
 497037        17:06:00              4
 497038        17:08:00              5
 ...                ...            ...
 2092178       18:10:00             24
 2092179       18:12:00             25
 2092180       18:13:30             26
 2092181       18:15:00             27
 2092182       18:17:00             28

 [196 rows x 5 columns],
 '102700_N..N33R':                                          trip_id stop_id arrival_time  \
 497136   BSP25GEN-N100-Weekday-00_102700_N..N33R    D43N     17:07:00
 497137   BSP25GEN-N100-Weekday-00_102700_N..N33R    N10N     17:11:00
 497138   BSP25GEN-N100-Weekday-00_102700_N..N33R    N09N     17:12:00
 497139   BSP25GEN-N100-Weekday-00_102700_N..N33R    N08N     17:14:00
 497140   BSP25GEN-N100-Weekday-00_102700_N..N33R    N07N     17:16:00
 ...                                          ...     ...          ...
 2092280           L0S9-N-1100-S01_102700_N..N33R    R06N     18:18:00
 2092281           L0S9-N-1100-S01_102700_N..N33R    R05N     18:20:00
 2092282           L0S9-N-1100-S01_102700_N..N33R    R04N     18:21:30
 2092283           L0S9-N-1100-S01_102700_N..N33R    R03N     18:23:00
 2092284           L0S9-N-1100-S01_102700_N..N33R    R01N     18:25:00

         departure_time  stop_sequence
 497136        17:07:00              1
 497137        17:11:00              2
 497138        17:12:00              3
 497139        17:14:00              4
 497140        17:16:00              5
 ...                ...            ...
 2092280       18:18:00             24
 2092281       18:20:00             25
 2092282       18:21:30             26
 2092283       18:23:00             27
 2092284       18:25:00             28

 [196 rows x 5 columns],
 '103300_N..N33R':                                          trip_id stop_id arrival_time  \
 497238   BSP25GEN-N100-Weekday-00_103300_N..N33R    D43N     17:13:00
 497239   BSP25GEN-N100-Weekday-00_103300_N..N33R    N10N     17:17:00
 497240   BSP25GEN-N100-Weekday-00_103300_N..N33R    N09N     17:18:00
 497241   BSP25GEN-N100-Weekday-00_103300_N..N33R    N08N     17:20:00
 497242   BSP25GEN-N100-Weekday-00_103300_N..N33R    N07N     17:22:00
 ...                                          ...     ...          ...
 2092382           L0S9-N-1100-S01_103300_N..N33R    R06N     18:24:00
 2092383           L0S9-N-1100-S01_103300_N..N33R    R05N     18:26:00
 2092384           L0S9-N-1100-S01_103300_N..N33R    R04N     18:27:30
 2092385           L0S9-N-1100-S01_103300_N..N33R    R03N     18:29:00
 2092386           L0S9-N-1100-S01_103300_N..N33R    R01N     18:31:00

         departure_time  stop_sequence
 497238        17:13:00              1
 497239        17:17:00              2
 497240        17:18:00              3
 497241        17:20:00              4
 497242        17:22:00              5
 ...                ...            ...
 2092382       18:24:00             24
 2092383       18:26:00             25
 2092384       18:27:30             26
 2092385       18:29:00             27
 2092386       18:31:00             28

 [196 rows x 5 columns],
 '104400_N..N33R': Empty DataFrame
 Columns: [trip_id, stop_id, arrival_time, departure_time, stop_sequence]
 Index: [],
 '105500_N..N33R': Empty DataFrame
 Columns: [trip_id, stop_id, arrival_time, departure_time, stop_sequence]
 Index: [],
 '106650_N..N33R':                                          trip_id stop_id arrival_time  \
 497600   BSP25GEN-N100-Weekday-00_106650_N..N33R    D43N     17:46:30
 497601   BSP25GEN-N100-Weekday-00_106650_N..N33R    N10N     17:50:30
 497602   BSP25GEN-N100-Weekday-00_106650_N..N33R    N09N     17:51:30
 497603   BSP25GEN-N100-Weekday-00_106650_N..N33R    N08N     17:53:30
 497604   BSP25GEN-N100-Weekday-00_106650_N..N33R    N07N     17:55:30
 ...                                          ...     ...          ...
 2092744           L0S9-N-1100-S01_106650_N..N33R    R06N     18:57:30
 2092745           L0S9-N-1100-S01_106650_N..N33R    R05N     18:59:30
 2092746           L0S9-N-1100-S01_106650_N..N33R    R04N     19:01:00
 2092747           L0S9-N-1100-S01_106650_N..N33R    R03N     19:02:30
 2092748           L0S9-N-1100-S01_106650_N..N33R    R01N     19:04:30

         departure_time  stop_sequence
 497600        17:46:30              1
 497601        17:50:30              2
 497602        17:51:30              3
 497603        17:53:30              4
 497604        17:55:30              5
 ...                ...            ...
 2092744       18:57:30             24
 2092745       18:59:30             25
 2092746       19:01:00             26
 2092747       19:02:30             27
 2092748       19:04:30             28

 [196 rows x 5 columns],
 '099650_N..S34R':                                          trip_id stop_id arrival_time  \
 496764   BSP25GEN-N100-Weekday-00_099650_N..S34R    R01S     16:36:30
 496765   BSP25GEN-N100-Weekday-00_099650_N..S34R    R03S     16:38:00
 496766   BSP25GEN-N100-Weekday-00_099650_N..S34R    R04S     16:39:30
 496767   BSP25GEN-N100-Weekday-00_099650_N..S34R    R05S     16:41:00
 496768   BSP25GEN-N100-Weekday-00_099650_N..S34R    R06S     16:43:00
 ...                                          ...     ...          ...
 2091908           L0S9-N-1100-S01_099650_N..S34R    N07S     17:40:30
 2091909           L0S9-N-1100-S01_099650_N..S34R    N08S     17:42:30
 2091910           L0S9-N-1100-S01_099650_N..S34R    N09S     17:46:30
 2091911           L0S9-N-1100-S01_099650_N..S34R    N10S     17:47:30
 2091912           L0S9-N-1100-S01_099650_N..S34R    D43S     17:51:30

         departure_time  stop_sequence
 496764        16:36:30              1
 496765        16:38:00              2
 496766        16:39:30              3
 496767        16:41:00              4
 496768        16:43:00              5
 ...                ...            ...
 2091908       17:40:30             24
 2091909       17:44:30             25
 2091910       17:46:30             26
 2091911       17:47:30             27
 2091912       17:51:30             28

 [196 rows x 5 columns],
 '101100_N..S34R':                                          trip_id stop_id arrival_time  \
 496928   BSP25GEN-N100-Weekday-00_101100_N..S34R    R01S     16:51:00
 496929   BSP25GEN-N100-Weekday-00_101100_N..S34R    R03S     16:52:30
 496930   BSP25GEN-N100-Weekday-00_101100_N..S34R    R04S     16:54:00
 496931   BSP25GEN-N100-Weekday-00_101100_N..S34R    R05S     16:55:30
 496932   BSP25GEN-N100-Weekday-00_101100_N..S34R    R06S     16:57:30
 ...                                          ...     ...          ...
 2092072           L0S9-N-1100-S01_101100_N..S34R    N07S     17:56:00
 2092073           L0S9-N-1100-S01_101100_N..S34R    N08S     17:58:00
 2092074           L0S9-N-1100-S01_101100_N..S34R    N09S     18:02:00
 2092075           L0S9-N-1100-S01_101100_N..S34R    N10S     18:03:00
 2092076           L0S9-N-1100-S01_101100_N..S34R    D43S     18:07:00

         departure_time  stop_sequence
 496928        16:51:00              1
 496929        16:52:30              2
 496930        16:54:00              3
 496931        16:55:30              4
 496932        16:57:30              5
 ...                ...            ...
 2092072       17:56:00             24
 2092073       18:00:00             25
 2092074       18:02:00             26
 2092075       18:03:00             27
 2092076       18:07:00             28

 [196 rows x 5 columns],
 '101400_N..S16R':                                          trip_id stop_id arrival_time  \
 496984   BSP25GEN-N100-Weekday-00_101400_N..S16R    Q05S     16:54:00
 496985   BSP25GEN-N100-Weekday-00_101400_N..S16R    Q04S     16:56:00
 496986   BSP25GEN-N100-Weekday-00_101400_N..S16R    Q03S     16:58:30
 496987   BSP25GEN-N100-Weekday-00_101400_N..S16R    B08S     17:00:30
 496988   BSP25GEN-N100-Weekday-00_101400_N..S16R    R14S     17:03:30
 ...                                          ...     ...          ...
 2092122           L0S9-N-1100-S01_101400_N..S16R    N07S     17:49:00
 2092123           L0S9-N-1100-S01_101400_N..S16R    N08S     17:51:00
 2092124           L0S9-N-1100-S01_101400_N..S16R    N09S     17:55:00
 2092125           L0S9-N-1100-S01_101400_N..S16R    N10S     17:56:00
 2092126           L0S9-N-1100-S01_101400_N..S16R    D43S     18:00:00

         departure_time  stop_sequence
 496984        16:54:00              1
 496985        16:56:00              2
 496986        16:58:30              3
 496987        17:00:30              4
 496988        17:03:30              5
 ...                ...            ...
 2092122       17:49:00             18
 2092123       17:53:00             19
 2092124       17:55:00             20
 2092125       17:56:00             21
 2092126       18:00:00             22

 [154 rows x 5 columns],
 '101600_N..S34R':                                          trip_id stop_id arrival_time  \
 497006   BSP25GEN-N100-Weekday-00_101600_N..S34R    R01S     16:56:00
 497007   BSP25GEN-N100-Weekday-00_101600_N..S34R    R03S     16:57:30
 497008   BSP25GEN-N100-Weekday-00_101600_N..S34R    R04S     16:59:00
 497009   BSP25GEN-N100-Weekday-00_101600_N..S34R    R05S     17:00:30
 497010   BSP25GEN-N100-Weekday-00_101600_N..S34R    R06S     17:02:30
 ...                                          ...     ...          ...
 2092150           L0S9-N-1100-S01_101600_N..S34R    N07S     18:00:00
 2092151           L0S9-N-1100-S01_101600_N..S34R    N08S     18:02:00
 2092152           L0S9-N-1100-S01_101600_N..S34R    N09S     18:06:00
 2092153           L0S9-N-1100-S01_101600_N..S34R    N10S     18:07:00
 2092154           L0S9-N-1100-S01_101600_N..S34R    D43S     18:11:00

         departure_time  stop_sequence
 497006        16:56:00              1
 497007        16:57:30              2
 497008        16:59:00              3
 497009        17:00:30              4
 497010        17:02:30              5
 ...                ...            ...
 2092150       18:00:00             24
 2092151       18:04:00             25
 2092152       18:06:00             26
 2092153       18:07:00             27
 2092154       18:11:00             28

 [196 rows x 5 columns],
 '102200_N..S34R':                                          trip_id stop_id arrival_time  \
 497108   BSP25GEN-N100-Weekday-00_102200_N..S34R    R01S     17:02:00
 497109   BSP25GEN-N100-Weekday-00_102200_N..S34R    R03S     17:03:30
 497110   BSP25GEN-N100-Weekday-00_102200_N..S34R    R04S     17:05:00
 497111   BSP25GEN-N100-Weekday-00_102200_N..S34R    R05S     17:06:30
 497112   BSP25GEN-N100-Weekday-00_102200_N..S34R    R06S     17:08:30
 ...                                          ...     ...          ...
 2092252           L0S9-N-1100-S01_102200_N..S34R    N07S     18:08:00
 2092253           L0S9-N-1100-S01_102200_N..S34R    N08S     18:10:00
 2092254           L0S9-N-1100-S01_102200_N..S34R    N09S     18:14:00
 2092255           L0S9-N-1100-S01_102200_N..S34R    N10S     18:15:00
 2092256           L0S9-N-1100-S01_102200_N..S34R    D43S     18:19:00

         departure_time  stop_sequence
 497108        17:02:00              1
 497109        17:03:30              2
 497110        17:05:00              3
 497111        17:06:30              4
 497112        17:08:30              5
 ...                ...            ...
 2092252       18:08:00             24
 2092253       18:12:00             25
 2092254       18:14:00             26
 2092255       18:15:00             27
 2092256       18:19:00             28

 [196 rows x 5 columns],
 '102900_N..S34R':                                          trip_id stop_id arrival_time  \
 497164   BSP25GEN-N100-Weekday-00_102900_N..S34R    R01S     17:09:00
 497165   BSP25GEN-N100-Weekday-00_102900_N..S34R    R03S     17:10:30
 497166   BSP25GEN-N100-Weekday-00_102900_N..S34R    R04S     17:12:00
 497167   BSP25GEN-N100-Weekday-00_102900_N..S34R    R05S     17:13:30
 497168   BSP25GEN-N100-Weekday-00_102900_N..S34R    R06S     17:15:30
 ...                                          ...     ...          ...
 2092308           L0S9-N-1100-S01_102900_N..S34R    N07S     18:15:00
 2092309           L0S9-N-1100-S01_102900_N..S34R    N08S     18:17:00
 2092310           L0S9-N-1100-S01_102900_N..S34R    N09S     18:21:00
 2092311           L0S9-N-1100-S01_102900_N..S34R    N10S     18:22:00
 2092312           L0S9-N-1100-S01_102900_N..S34R    D43S     18:26:00

         departure_time  stop_sequence
 497164        17:09:00              1
 497165        17:10:30              2
 497166        17:12:00              3
 497167        17:13:30              4
 497168        17:15:30              5
 ...                ...            ...
 2092308       18:15:00             24
 2092309       18:19:00             25
 2092310       18:21:00             26
 2092311       18:22:00             27
 2092312       18:26:00             28

 [196 rows x 5 columns],
 '103750_N..S34R':                                          trip_id stop_id arrival_time  \
 497266   BSP25GEN-N100-Weekday-00_103750_N..S34R    R01S     17:17:30
 497267   BSP25GEN-N100-Weekday-00_103750_N..S34R    R03S     17:19:00
 497268   BSP25GEN-N100-Weekday-00_103750_N..S34R    R04S     17:20:30
 497269   BSP25GEN-N100-Weekday-00_103750_N..S34R    R05S     17:22:00
 497270   BSP25GEN-N100-Weekday-00_103750_N..S34R    R06S     17:24:00
 ...                                          ...     ...          ...
 2092410           L0S9-N-1100-S01_103750_N..S34R    N07S     18:21:30
 2092411           L0S9-N-1100-S01_103750_N..S34R    N08S     18:23:30
 2092412           L0S9-N-1100-S01_103750_N..S34R    N09S     18:27:30
 2092413           L0S9-N-1100-S01_103750_N..S34R    N10S     18:28:30
 2092414           L0S9-N-1100-S01_103750_N..S34R    D43S     18:32:30

         departure_time  stop_sequence
 497266        17:17:30              1
 497267        17:19:00              2
 497268        17:20:30              3
 497269        17:22:00              4
 497270        17:24:00              5
 ...                ...            ...
 2092410       18:21:30             24
 2092411       18:25:30             25
 2092412       18:27:30             26
 2092413       18:28:30             27
 2092414       18:32:30             28

 [196 rows x 5 columns],
 '104550_N..S34R':                                          trip_id stop_id arrival_time  \
 497368   BSP25GEN-N100-Weekday-00_104550_N..S34R    R01S     17:25:30
 497369   BSP25GEN-N100-Weekday-00_104550_N..S34R    R03S     17:27:00
 497370   BSP25GEN-N100-Weekday-00_104550_N..S34R    R04S     17:28:30
 497371   BSP25GEN-N100-Weekday-00_104550_N..S34R    R05S     17:30:00
 497372   BSP25GEN-N100-Weekday-00_104550_N..S34R    R06S     17:32:00
 ...                                          ...     ...          ...
 2092512           L0S9-N-1100-S01_104550_N..S34R    N07S     18:29:30

In [3]:
"""
Combining static and real time schedule to compute delay information
"""
import pandas as pd
from nyct_gtfs.gtfs_static_types import Stations
from datetime import datetime

stations = Stations()

# === Shared delay calculation logic ===
def process_trains(train_list, direction_label):
    results = []

    for train in train_list:
        trip_id = train.trip_id
        current_time = train.last_position_update
        stop_id = train.location

        if stop_id and trip_id:
            sched = stop_times[
                stop_times.trip_id.str.contains(trip_id, na=False) &
                (stop_times.stop_id == stop_id)
            ][["arrival_time", "departure_time"]]

            if not sched.empty:
                try:
                    scheduled_time = datetime.strptime(sched["arrival_time"].iloc[0], "%H:%M:%S").time()
                    scheduled_dt = pd.Timestamp.combine(current_time.date(), scheduled_time)
                    delay = (current_time - scheduled_dt).total_seconds() / 60.0

                    results.append({
                        "trip_id": trip_id,
                        "stop_id_raw": stop_id,
                        "stop_id": stations.get_station_name(stop_id),
                        "timestamp": current_time,
                        "delay_min": round(delay,2),
                        "status": "on_time" if abs(delay) < 1 else "delayed" if delay > 0 else "early",
                        "direction": direction_label
                    })
                except Exception as e:
                    print(f"Error parsing time for {trip_id} at {stop_id}: {e}")

    df = pd.DataFrame(results)

    # Add stop_sequence by fuzzy match
    def get_stop_sequence(row):
        match = stop_times[
            stop_times.trip_id.str.contains(row["trip_id"], na=False) &
            (stop_times.stop_id == row["stop_id_raw"])
        ]
        if not match.empty:
            return match.iloc[0]["stop_sequence"]
        else:
            return None

    df["stop_sequence"] = df.apply(get_stop_sequence, axis=1)
    df = df.sort_values(by=["trip_id", "stop_sequence"]).reset_index(drop=True)

    return df


# === Run for both directions ===
northbound_df = process_trains(northbound_trains, direction_label="N")
southbound_df = process_trains(southbound_trains, direction_label="S")

# === Combine for full view ===
all_delays_df = pd.concat([northbound_df, southbound_df]).sort_values(by=["trip_id", "stop_sequence"]).reset_index(drop=True)

# === Rush hour logic ===
def classify_rush_hour(ts):
    hour = ts.hour
    if 7 <= hour < 10:
        return "morning"
    elif 16 <= hour < 19:
        return "evening"
    else:
        return None
    
# === Log ===
all_delays_df["rush_hour"] = all_delays_df["timestamp"].apply(classify_rush_hour)

all_delays_df

,trip_id,stop_id_raw,stop_id,timestamp,delay_min,status,direction,stop_sequence,rush_hour
0,099300_N..N33R,R03N,Astoria Blvd,2025-07-28 17:45:52,-4.63,early,N,27,evening
1,099650_N..S34R,N10S,86 St,2025-07-28 17:45:52,-1.63,early,S,27,evening
2,100200_N..N16R,Q03N,72 St,2025-07-28 17:45:32,2.53,delayed,N,20,evening
3,101100_N..S34R,N08S,Kings Hwy,2025-07-28 17:45:52,-12.13,early,S,25,evening
4,101200_N..N33R,R14N,57 St-7 Av,2025-07-28 17:45:52,-3.63,early,N,19,evening
5,101400_N..S16R,N05S,18 Av,2025-07-28 17:45:54,-0.10,on_time,S,16,evening
6,101600_N..S34R,R36S,36 St,2025-07-28 17:44:42,-0.80,on_time,S,17,evening
7,101900_N..N33R,R17N,34 St-Herald Sq,2025-07-28 17:45:52,-4.13,early,N,16,evening
8,102200_N..S34R,Q01S,Canal St,2025-07-28 17:37:47,1.78,delayed,S,15,evening
9,102700_N..N33R,R31N,Atlantic Av-Barclays Ctr,2025-07-28 17:39:07,1.62,delayed,N,13,evening
10,102900_N..S34R,Q01S,Canal St,2025-07-28 17:42:27,1.45,delayed,S,15,evening
11,103300_N..N33R,R31N,Atlantic Av-Barclays Ctr,2025-07-28 17:44:35,1.08,delayed,N,13,evening
12,103750_N..S34R,R20S,14 St-Union Sq,2025-07-28 17:45:52,0.37,on_time,S,14,evening
13,104550_N..S34R,R14S,57 St-7 Av,2025-07-28 17:45:52,1.37,delayed,S,10,evening
14,105400_N..S34R,R09S,Queensboro Plaza,2025-07-28 17:45:52,1.87,delayed,S,7,evening
15,106450_N..S34R,R04S,30 Av,2025-07-28 17:45:52,-1.63,early,S,3,evening
16,106650_N..N33R,D43N,Coney Island-Stillwell Av,2025-07-28 17:46:30,0.00,on_time,N,1,evening

In [4]:
import datetime
import pandas as pd
from sqlalchemy import create_engine, text

# === Database config ===
DB_USER = "neondb_owner"
DB_PASSWORD = ""  # Replace with the password you revealed
DB_HOST = "ep-spring-truth-ae312q45-pooler.c-2.us-east-2.aws.neon.tech"
DB_PORT = "5432"
DB_NAME = "neondb"

# === Create DB engine ===
engine = create_engine(f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

# === Create tables ===
create_train_delays = """
CREATE TABLE IF NOT EXISTS train_delays (
    id SERIAL PRIMARY KEY,
    trip_id TEXT,
    stop_id TEXT,
    station_name TEXT,
    timestamp TIMESTAMP,
    delay_min REAL,
    status TEXT,
    direction TEXT,
    stop_sequence INTEGER,
    rush_hour TEXT
);
"""

with engine.connect() as conn:
    conn.execute(text(create_train_delays))
    print("Table created.")

# === Clean and insert delay data ===
if not all_delays_df.empty:
    delay_cols = ['trip_id', 'stop_id_raw', 'stop_id', 'timestamp', 'delay_min', 'status', 'direction', 'stop_sequence', 'rush_hour']
    df = all_delays_df[delay_cols].copy()
    df.columns = ['trip_id', 'stop_id', 'station_name', 'timestamp', 'delay_min', 'status', 'direction', 'stop_sequence', 'rush_hour']
    df.to_sql('train_delays', engine, if_exists='append', index=False)
    print(f"Inserted {len(df)} delay records.")
else:
    print("No delay data found.")

Table created.
Inserted 13 delay records.

In [9]:
# """
# Build Hourly Features + Labels from Postgres
# """
# import pandas as pd
# 
# # === Get hourly aggregated delay data ===
# delay_sql = """
#     SELECT 
#         DATE_TRUNC('hour', timestamp) AS hour,
#         COUNT(*) FILTER (WHERE delay_min > 1) * 1.0 / COUNT(*) AS delay_rate,
#         COUNT(*) AS total_trips,
#         MAX(rush_hour) AS rush_hour  -- could be 'morning', 'evening', or NULL
#     FROM train_delays
#     GROUP BY hour
#     ORDER BY hour
# """
# 
# # === Get matching weather data ===
# weather_sql = """
#     SELECT 
#         time AS hour,
#         temperature_f,
#         precipitation,
#         snowfall,
#         humidity,
#         windspeed
#     FROM weather_hourly
# """
# 
# # === Load from Postgres ===
# df_delays = pd.read_sql(delay_sql, engine)
# df_weather = pd.read_sql(weather_sql, engine)
# 
# # === Merge both datasets on hour
# df = pd.merge(df_delays, df_weather, on="hour", how="inner")
# 
# # === Add time-based features
# df["hour_of_day"] = df["hour"].dt.hour
# df["day_of_week"] = df["hour"].dt.dayofweek
# df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)
# 
# # === Drop incomplete rows
# df = df.dropna()
# 
# # === Show preview
# df

,hour,delay_rate,total_trips,rush_hour,temperature_f,precipitation,snowfall,humidity,windspeed,hour_of_day,day_of_week,is_weekend
0,2025-07-24 08:00:00,0.390244,41,morning,72.6,0.0,0.0,64.0,6.6,8,3,0
1,2025-07-24 17:00:00,0.333333,36,evening,87.9,0.0,0.0,47.0,10.7,17,3,0